name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
      - uses: warrenbuckley/Setup-Nuget@v1
      - uses: warrenbuckley/Setup-MSBuild@v1
      - uses: Malcolmnixon/Setup-VSTest@2

      - name: Restore
        run: nuget restore MFWSSamplesAndLibraries.sln

      - name: Test
        working-directory: Libraries\MFaaP.MFWSClient.Tests
        run: |
          msbuild /p:Configuration=Release
          vstest.console .\bin\Release\MFaaP.MFWSClient.Tests.dll
  publish-nuget:
    runs-on: windows-latest
    needs: [test]
    # tag a release as v1.0.0....
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@master
      - uses: warrenbuckley/Setup-MSBuild@v1
      - uses: warrenbuckley/Setup-Nuget@v1

      - name: Restore
        run: nuget restore MFWSSamplesAndLibraries.sln

      - name: Extract tag version
        run: |
          $env:GITHUB_REF -match "^refs/tags/v(.+)"
          $versionTag = $Matches[1]
          Write-Host "::set-env name=VERSION_TAG::$versionTag"

      - name: Publish
        working-directory: Libraries\MFaaP.MFWSClient
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
          NUGET_SYMBOL_SOURCE: ${{ secrets.NUGET_SYMBOL_SOURCE }}
          NUGET_ACCESS_TOKEN: ${{ secrets.NUGET_ACCESS_TOKEN }}
        run: |
          msbuild /p:Configuration=Release
          nuget pack -Version $env:VERSION_TAG -Properties Configuration=Release -Symbols -OutputDirectory out
          dir out
          nuget push out\*.nupkg $env:NUGET_ACCESS_TOKEN -Source $env:NUGET_SOURCE -SymbolSource $env:NUGET_SYMBOL_SOURCE -SymbolApiKey $env:NUGET_ACCESS_TOKEN
